# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Facebook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'
  pod 'RxKeyboard'

  # Kakao
  pod 'RxKakaoSDKCommon'
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'

  # Alamofire
  pod 'RxAlamofire'

  # Kingfisher
  pod 'Kingfisher'
  
  # Snapkit
  pod 'SnapKit', '~> 5.0.0'

end
