# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Careerly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Careerly

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'

  # Kakao
  pod 'RxKakaoSDKCommon'
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'

  # Alamofire
  pod 'RxAlamofire'

  # Kingfisher
  pod 'Kingfisher'
  
end
